version: '3.0'

services:
  webserver:
    build: .
    container_name: webservice
    ports:
      - "8088:8088"
  oracle:
    image: oracle/database:21.3.0-xe
    container_name: oracle21
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PWD: booble34
    volumes:
      - ./data:\oraclDB
  app:
    build: C:\Users\Vitalii\IdeaProjects\OnlineLearningKRSavostian
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - oracle
      - webserver
    environment:
      TZ: Europe/Kiev
