version: '3.0'

services:
  webserver:
    build: https://github.com/VitaliyCC/ScheduleWebService.git
    container_name: webservice
    ports:
      - "8088:8088"

  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: postgress
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
         - ./data:\oraclDB
  app:
    build:  https://github.com/VitaliyCC/OnlineLearningApp.git
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - webserver

